# 31.08.23

# Methods to Create Numpy Arrays

## arange()
### This method returns evenly spaced values b/w the given intervals excluding the end limit.
### The values are generated based on the step value which is 1 by default.

In [3]:
import numpy as np

# start and end limit
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# step val=3
np.arange(2,12,3)

array([ 2,  5,  8, 11])

## linspace()
### This method returns the given number of evenly spaced values, b/w the given intervals.
### By default, the number of values b/w a given interval is 50.

In [9]:
# Generating values b/w 0 and 10
arr = np.linspace(0,10)
print(arr)
print('Len(arr): ', len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Len(arr):  50


In [10]:
# Number of values = 5
print(np.linspace(2,4,4))

[2.         2.66666667 3.33333333 4.        ]


# Zeroes and Ones

## zeros()
### This method returns array of given shape filled with zeros.

In [11]:
# 1D
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
# 2D
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# 3D
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## ones()
### This method returns an array of given shape filled with ones.

In [14]:
# 1D
np.ones(3)

array([1., 1., 1.])

In [15]:
# 2D
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
# 3D
np.ones([2,5,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# Full and Eye

## full()
### Returns an array of given shape, filled with given value, irrespective of datatype.

In [17]:
# shape=5, val=3
np.full(5,3)

array([3, 3, 3, 3, 3])

In [18]:
# shape=[2,3], val=4
np.full([2,3],4)

array([[4, 4, 4],
       [4, 4, 4]])

## eye()
### Returns an identity matrix for the given shape.

In [19]:
# 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# 3x4 mat
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Random

## Numpy has numerous ways to create random number arrays.
## Random numbers can be created for the required length, from a Uniform Distribution by just passing the value of required length to the random.rand() fn.

In [24]:
# Generating 5 random numbers from a Uniform Distribution
np.random.rand(5)

array([0.60743254, 0.26105137, 0.25613827, 0.11505566, 0.99246472])

## Similarly, to generate random numbers from a Normal Distribution, random.randn() fn is used.

In [25]:
# Generating 5 random numbers from a Normal Distribution
np.random.randn(5)

array([ 0.36907456, -0.10894859, -0.01565327,  0.10023505, -0.35100981])

## Random numbers of type 'integer' can also be generated using random.randint() fn.

In [33]:
# Generating a 1D array of size 5 having random integers in the range [1,10)
# np.random.randint(1,10,size=5)
np.random.randint(1,10,5)

array([3, 8, 4, 4, 4])

## Similarly, 2D arrays of random numbers can also be created by passing the shape instead of number of values.

In [34]:
# Random int val high=100 and shape=(3,5)
rand_arr = np.random.randint(100,size=(3,5))
print(rand_arr)
print(type(rand_arr))

[[65 74 88 77 61]
 [45 94 72 51  3]
 [53 26 96 70 44]]
<class 'numpy.ndarray'>


## To generate a random number from a predefined set of values present in an array, the choice() method can be used.
## The choice() method takes an arrays as a parameter and randomly returns the values based on the size.

In [37]:
# Returning a single random value from the array
rv = np.random.choice([2,4,6,3,5,7])
print(rv)

7


In [38]:
# Returning a 3x5 matrix of random values from the array
rv_mat = np.random.choice([2,3,4,5,6,7], size=(3,5))
# sampling to create an nd-array

print(rv_mat)
print(type(rv_mat))

[[7 2 7 7 2]
 [2 5 3 2 5]
 [4 3 5 2 4]]
<class 'numpy.ndarray'>
